### PR TITLE
Created a Command-Line Interface

### PR DESCRIPTION
**Pull request by MahmoudElsayad**
Things i added to the python code:
  1- Created a command-line interface using "Docopt"
  2- Working for python 3.0x
  3- Retrieving publications, and abstract too
  4- Added 500ms delay for the blocking of google issue

### CODE REVIEW

**Comment by WittmannF** [comment]
Hi @MahmoudElsayad! Thank you so much for suggesting a pull request! I am quite admired by the effort that you put here! I especially liked the 500ms delay to solve the robot blocking :) I am just wondering if it is necessary to use `docopt` to read the command line arguments. Apparently the user would have to install it. Maybe it could be used `argparse` since it is native on Python. I can do it later when I find some time :)

**Comment by MahmoudElsayad** [comment]
You are already using pandas, **BeautifulSoup** and **Matplotlib**, and **docopt** is an overall better solution than argparse for the full control of the --help output (argparse can do it of course, but, you will have to implement an argparse “formatter class", which is a real pain), also maintainability is generally better in the docopt case, **Octparse** is better for bigger projects, Argparse is just a pain thats why heroku created Octparse, but that's not the case here.

**Comment by WittmannF** [comment]
Pandas and Matplotlib are usually already available for anaconda users. But, that's a good point regarding BeautifulSoup. I am going to merge it. Thank you again for the contribution!

**Comment by WittmannF** [comment]
@MahmoudElsayad , I was trying your code, and I got only 10 results, instead of 200. Can you try in your machine as well to check if this is a bug? Here's what I did:

```
git clone https://github.com/WittmannF/sort-google-scholar.git
cd sort-google-scholar/
python google_scholar_sort.py "Bioinformatics" --results=200
```

The .CSV file has only 10 lines.

**Comment by WittmannF** [comment]
@MahmoudElsayad I will be reverting the pull request if I don't hear back from you in one week. Thank you for your understanding.

**Pull request merged**
